Refactor project
Museu-da-Pessoa-XP/frontend pull request #12
Opened 2020-12-11 02:22 UTC by AndrewIjano

Nesse PR tem várias refatorações:
- Reformatei todo o código com o Prettier para ficar padronizado. Agora próximas edições vão manter automaticamente a padronização com o git hook + prettier;
- Coloquei props validation em todos os components que precisavam;
- Removi muito código que não estava sendo usado;
- Refatorei os components do FormHistoria para ficar mais claro o que está acontecendo. Sugiro olhar com atenção para ver se foram as melhores decisões;
- Removi a pasta `styles` que não estava sendo utilizada.

Essas são modificações super úteis, então sugiro ver com cuidado. Pense como uma pessoa que vai ver nosso código pela primeira vez, que serão as próximas pessoas que vão ver o nosso projeto

2020-12-11 15:29 UTC, tutss requested changes

2020-12-11 15:29 UTC, tutss commented on src/components/forms/FormHistoria.js
> +            <StepLabel />
Não precisa mais de um `return` aqui?

2020-12-11 15:29 UTC, tutss commented on src/components/forms/FormHistoria.test.js
Não seria melhor colocar todos os arquivos de teste em uma pasta separada?

2020-12-11 15:46 UTC, AndrewIjano commented on src/components/forms/FormHistoria.js
> +            <StepLabel />
Hm, não

Fazer `(bar) => foo(bar)` é a mesma coisa que `(bar) => { return foo(bar) }` ou `function fooBar(bar) { return foo(bar) }`. 

A notação com return só é útil se vc precisa de comandos (não expressões), como
```javascript
(bar) => {
  const obj = new Obj();
  obj.add(bar);
  return obj;
}
```
Como no nosso caso não precisa, acaba ficando desnecessário.

2020-12-11 15:49 UTC, AndrewIjano commented on src/components/forms/FormHistoria.test.js
Ah, não sei. Como esses são testes de unidade, pra mim faz sentido eles ficarem próximos do código. Achei um artigo que fala isso:
![image](https://user-images.githubusercontent.com/37511135/101924256-35088b00-3baf-11eb-9d22-ce4c8b9f870a.png)

Faz sentido?

2020-12-11 16:01 UTC, AndrewIjano commented on src/components/forms/FormHistoria.test.js
Aliás, queria sugerir outra coisa. Acha que faz sentido refatorar o código do jeito que está agora? Tinha pensado em algo do tipo:
```
|- src/
   |- components/
      |- pages/
         |- index.js
         |- FormPersonalData.js
         |- FormSelectMediaType.js
         |- ...
      |- FormHistoria.js  (FormHistoria separado das páginas)
      |- FormHistoria.test.js
      |- sendForm.js
      |- SelectorMediaType.js (components pequenos que são dependências das páginas)
      |- ...
   |- App.js
   |- index.js
   .
   .
   . 
```

Ou até
```
|- src/
   |- components/
      |- pages/
         |- index.js
         |- FormPersonalData/
            |- index.js
            |- FormPersonalData.js
         |- FormSelectMediaType
            |- index.js
            |- FormSelectMediaType.js
            |- SelectorMediaType.js (components pequenos juntos na página)
         |- ...
      |- FormHistoria.js
      |- FormHistoria.test.js
      |- sendForm.js (só esses 3 arquivos no components/)
   |- App.js
   |- index.js
   .
   .
   . 
```

O que vc acha?

2020-12-11 16:24 UTC, robonauta commented on src/components/forms/FormHistoria.test.js
I'd suggest to rename "*Historia" to "Story" to keep name consistency.

2020-12-11 17:05 UTC, tutss commented on src/components/forms/FormHistoria.test.js
Gosto da primeira opção, acho que fica segmentado no ponto ideal

2020-12-11 21:11 UTC, AndrewIjano commented on src/components/forms/FormHistoria.test.js
Done

2020-12-14 14:12 UTC, robonauta approved these changes
lgtm :+1:

2020-12-14 21:26 UTC, RenanSchwyz approved these changes

2020-12-14 21:30 UTC, merged